export const usersData = [
  {
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    gender: "Female",
    dob: new Date("1990-05-15").toISOString(),
    address: "123 Main St, Springfield, IL, USA",
    phone: "",
    title: "Software Engineer",
    avatarUrl: "",
    createdAt: new Date("2023-04-10T09:00:00Z").toISOString(),
    roles: ["Admin"],
  },
  {
    firstName: "Bob",
    lastName: "Smith",
    email: "bob.smith@example.com",
    gender: "Male",
    dob: new Date("1985-10-22").toISOString(),
    address: "456 Oak Ave, Metropolis, NY, USA",
    phone: "+1-555-987-6543",
    title: "Product Manager",
    avatarUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    createdAt: new Date("2022-11-05T14:30:00Z").toISOString(),
    roles: ["User"],
  },
  {
    firstName: "Carla",
    lastName: "Nguyen",
    email: "carla.nguyen@example.com",
    gender: "Female",
    dob: new Date("1993-02-08").toISOString(),
    address: "789 Pine Rd, Emerald City, WA, USA",
    phone: "+1-555-654-3210",
    title: "UX Designer",
    avatarUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    createdAt: new Date("2023-01-20T11:15:00Z").toISOString(),
    roles: ["Reviewer"],
  },
  {
    firstName: "David",
    lastName: "Lee",
    email: "david.lee@example.com",
    gender: "Male",
    dob: new Date("1988-09-17").toISOString(),
    address: "321 Elm St, Gotham, NJ, USA",
    phone: "+1-555-321-0987",
    title: "Data Analyst",
    avatarUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    createdAt: new Date("2022-07-01T08:00:00Z").toISOString(),
    roles: ["User"],
  },
  {
    firstName: "Ella",
    lastName: "Martinez",
    email: "ella.martinez@example.com",
    gender: "Female",
    dob: new Date("1995-12-25").toISOString(),
    address: "654 Maple Ave, Star City, TX, USA",
    phone: "+1-555-555-1212",
    title: "Marketing Coordinator",
    avatarUrl: "https://randomuser.me/api/portraits/women/5.jpg",
    createdAt: new Date("2023-03-18T12:00:00Z").toISOString(),
    roles: ["Editor"],
  },
  {
    firstName: "Frank",
    lastName: "Turner",
    email: "frank.turner@example.com",
    gender: "Male",
    dob: new Date("1980-03-04").toISOString(),
    address: "102 Birch Blvd, Central City, CO, USA",
    phone: "+1-555-121-2121",
    title: "Network Engineer",
    avatarUrl: "https://randomuser.me/api/portraits/men/6.jpg",
    createdAt: new Date("2021-12-15T16:45:00Z").toISOString(),
    roles: ["User"],
  },
  {
    firstName: "Grace",
    lastName: "Kim",
    email: "grace.kim@example.com",
    gender: "Female",
    dob: new Date("1991-08-11").toISOString(),
    address: "909 Cedar Ln, Riverdale, CA, USA",
    phone: "+1-555-678-4321",
    title: "HR Manager",
    avatarUrl: "https://randomuser.me/api/portraits/women/7.jpg",
    createdAt: new Date("2023-01-10T10:10:00Z").toISOString(),
    roles: ["Admin"],
  },
  {
    firstName: "Henry",
    lastName: "Adams",
    email: "henry.adams@example.com",
    gender: "Male",
    dob: new Date("1992-06-30").toISOString(),
    address: "203 Walnut St, Smallville, OH, USA",
    phone: "+1-555-444-3333",
    title: "QA Engineer",
    avatarUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    createdAt: new Date("2023-04-01T09:30:00Z").toISOString(),
    roles: ["Reviewer"],
  },
  {
    firstName: "Isla",
    lastName: "Brown",
    email: "isla.brown@example.com",
    gender: "Female",
    dob: new Date("1994-11-09").toISOString(),
    address: "56 Aspen Dr, Twin Peaks, WA, USA",
    phone: "+1-555-222-9876",
    title: "Graphic Designer",
    avatarUrl: "https://randomuser.me/api/portraits/women/9.jpg",
    createdAt: new Date("2022-06-12T11:00:00Z").toISOString(),
    roles: ["Editor"],
  },
  {
    firstName: "Jack",
    lastName: "White",
    email: "jack.white@example.com",
    gender: "Male",
    dob: new Date("1987-01-05").toISOString(),
    address: "84 Fir St, Sunnydale, FL, USA",
    phone: "+1-555-333-6789",
    title: "DevOps Engineer",
    avatarUrl: "https://randomuser.me/api/portraits/men/10.jpg",
    createdAt: new Date("2021-10-30T15:00:00Z").toISOString(),
    roles: ["User"],
  },
  {
    firstName: "Kara",
    lastName: "Davies",
    email: "kara.davies@example.com",
    gender: "Female",
    dob: new Date("1990-04-28").toISOString(),
    address: "72 Palm Rd, Hill Valley, CA, USA",
    phone: "+1-555-111-2233",
    title: "Operations Manager",
    avatarUrl: "https://randomuser.me/api/portraits/women/11.jpg",
    createdAt: new Date("2023-02-14T13:10:00Z").toISOString(),
    roles: ["Admin"],
  },
  {
    firstName: "Leo",
    lastName: "Martin",
    email: "leo.martin@example.com",
    gender: "Male",
    dob: new Date("1989-07-13").toISOString(),
    address: "87 Willow St, Elmsford, NY, USA",
    phone: "+1-555-888-1111",
    title: "System Architect",
    avatarUrl: "https://randomuser.me/api/portraits/men/12.jpg",
    createdAt: new Date("2022-09-17T10:30:00Z").toISOString(),
    roles: ["User"],
  },
  {
    firstName: "Maya",
    lastName: "Scott",
    email: "maya.scott@example.com",
    gender: "Female",
    dob: new Date("1996-10-19").toISOString(),
    address: "10 Redwood Ct, Arcadia, AZ, USA",
    phone: "+1-555-999-0000",
    title: "Frontend Developer",
    avatarUrl: "https://randomuser.me/api/portraits/women/13.jpg",
    createdAt: new Date("2023-05-01T08:20:00Z").toISOString(),
    roles: ["Reviewer"],
  },
  {
    firstName: "Nathan",
    lastName: "Wright",
    email: "nathan.wright@example.com",
    gender: "Male",
    dob: new Date("1991-03-12").toISOString(),
    address: "23 Spruce St, Beacon, NY, USA",
    phone: "+1-555-777-6666",
    title: "Backend Developer",
    avatarUrl: "https://randomuser.me/api/portraits/men/14.jpg",
    createdAt: new Date("2022-12-25T07:45:00Z").toISOString(),
    roles: ["Editor"],
  },
  {
    firstName: "Olivia",
    lastName: "Bennett",
    email: "olivia.bennett@example.com",
    gender: "Female",
    dob: new Date("1993-09-21").toISOString(),
    address: "19 Peach Ave, Harmony, SC, USA",
    phone: "+1-555-321-9999",
    title: "Technical Writer",
    avatarUrl: "https://randomuser.me/api/portraits/women/15.jpg",
    createdAt: new Date("2023-01-01T12:15:00Z").toISOString(),
    roles: ["User"],
  },
  {
    firstName: "Paul",
    lastName: "Reed",
    email: "paul.reed@example.com",
    gender: "Male",
    dob: new Date("1983-02-18").toISOString(),
    address: "35 Canyon Rd, Boulder, CO, USA",
    phone: "+1-555-555-0000",
    title: "IT Specialist",
    avatarUrl: "https://randomuser.me/api/portraits/men/16.jpg",
    createdAt: new Date("2022-08-08T09:00:00Z").toISOString(),
    roles: ["Admin"],
  },
  {
    firstName: "Quinn",
    lastName: "Simmons",
    email: "quinn.simmons@example.com",
    gender: "Non-Binary",
    dob: new Date("1997-01-30").toISOString(),
    address: "7 Bay St, Portview, MA, USA",
    phone: "+1-555-616-2727",
    title: "Content Strategist",
    avatarUrl: "https://randomuser.me/api/portraits/lego/1.jpg",
    createdAt: new Date("2023-02-20T10:30:00Z").toISOString(),
    roles: ["Editor"],
  },
  {
    firstName: "Rachel",
    lastName: "Stone",
    email: "rachel.stone@example.com",
    gender: "Female",
    dob: new Date("1992-06-15").toISOString(),
    address: "41 Ocean Dr, Venice, CA, USA",
    phone: "+1-555-101-2020",
    title: "Recruiter",
    avatarUrl: "https://randomuser.me/api/portraits/women/18.jpg",
    createdAt: new Date("2023-03-12T13:15:00Z").toISOString(),
    roles: ["Reviewer"],
  },
  {
    firstName: "Steve",
    lastName: "Harper",
    email: "steve.harper@example.com",
    gender: "Male",
    dob: new Date("1986-11-08").toISOString(),
    address: "120 Lakeview Blvd, Lakeside, MI, USA",
    phone: "+1-555-212-3434",
    title: "Sales Manager",
    avatarUrl: "https://randomuser.me/api/portraits/men/19.jpg",
    createdAt: new Date("2023-04-08T14:00:00Z").toISOString(),
    roles: ["User"],
  },
];
